# Generated by Django 3.2.25 on 2024-03-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='author',
        ),
    ]
