# Generated by Django 3.2.25 on 2024-03-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_drink_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='ingredients',
            field=models.TextField(default='unknown'),
        ),
    ]
